### ISSUE TITLE
Release 1.2.0 Steps

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#112]
### Release Version V1.2.0

- [x] Use latest master as candidate V1.2.0 of WebAPI and deploy to development
- [x] Generate WebAPI Release Notes
- [x] Complete user acceptance testing
- [x] Obtain sign off
- [x] Publish Release
- [x] Communicate production change to team
- [x] Update OHDSI.org
- [x] Communicate release via OHDSI forums
