### ISSUE TITLE
V1.3.0 Release

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#119]
### Release Version V1.3.0

- [x] Create release branch for v1.3.0
- [x] Use latest master as candidate V1.3.0 of WebAPI and deploy to development
- [x] Generate WebAPI Release Notes
- [x] Complete user acceptance testing
- [x] Obtain sign off
- [x] Publish Release
- [x] Update "released" branch to obtain latest stable build for OHDSI.org
- [x] Communicate production change to team
- [x] Update OHDSI.org
- [x] Communicate release via OHDSI forums
