### ISSUE TITLE
Release v2.7.2

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#1207]
### Release Version V2.7.2
- [x] Use branch v2.7.2-rc of Atlas & WebAPI and deploy to development. Ensure that all pom.xml references are using released libraries:

|dependency   	|owner   	|pom reference   	|target version   	|changes   	|
|---	|---	|---	|---	|---	|
|SqlRender    	|@schuemie | 1.6.1-SNAPSHOT  	|1.6.2   	| https://github.com/OHDSI/SqlRender/compare/v1.6.1...master  	|
|FeatureExtraction  	|@schuemie |2.2.0   	|2.2.4   	|https://github.com/OHDSI/FeatureExtraction/compare/v2.2.1...v2.2.4   	|
|Hydra 	|@schuemie |0.0.4   	|0.0.5   	|https://github.com/OHDSI/Hydra/compare/v0.0.4...v0.0.5   	|
|circe-be   	|@chrisknoll |1.8.0-SNAPSHOT   	|1.8.0   	|https://github.com/OHDSI/circe-be/compare/v1.7.3...master   	|
|standardized-analysis-specs & standardized-analysis-utils    	|@pavgra |1.2.0-SNAPSHOT   	|1.2.0   	|https://github.com/OHDSI/StandardizedAnalysisAPI/compare/v1.1.0...master   	|
|SkeletonCohortCharacterization   	|@pavgra |1.0.0-SNAPSHOT   	|1.0.0   	|**initial release**   	|

- [x] Back merge Atlas v2.7.2-rc branch into master
- [x] Back merge WebAPI's v2.7.2-rc branch into master
- [x] Complete testing, obtain sign off and post testing results
- [x] Generate WebAPI Release Notes
- [ ] Publish Release
- [x] Update wikis to reflect any install/setup instructions
- [ ] Update OHDSI.org
- [ ] Communicate release via OHDSI forums
