### ISSUE TITLE
Release v1.4.0

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#130]
### Release Version V1.4.0
- [x] Use latest master as candidate V1.4.0 of Atlas and deploy to development
- [x] Generate WebAPI Release Notes
- [x] Complete user acceptance testing
- [x] Obtain sign off
- [x] Publish Release
- [x] Communicate production change to team
- [x] Update OHDSI.org
- [x] Communicate release via OHDSI forums
