### ISSUE TITLE
Relase 1.5.0

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#154]
### Release Version V1.5.0
- [x] Use latest master as candidate V1.4.0 of Atlas and deploy to development
- [x] Generate WebAPI Release Notes
- [x] Complete user acceptance testing
- [x] Obtain sign off
- [x] Publish Release
- [x] Communicate production change to team
- [x] Update OHDSI.org
- [x] Communicate release via OHDSI forums

Included changes:
Fix in results table qualifier in /cohortcomparison/sql/pop_prop_score.sql.
Fix for #137.
Cohort Definition optimizations: query and temp table performance improvements.
Fix for #144: Generate Cohort results in 'Completed' status when exception is thrown.
Fix for #146: Fixes for demographic criteria.
Fix for #155: Handle empty criteria groups gracefully.

HTTP Verb normalization: in preparation for the security layer to be introduced in version 2.0.0.
IR Analysis: added distribution calculations for TAR and TTO, and provided export to zip function.
Cohort Definition Correlated Criteria
Cohort Definition Censoring Events
