### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#179]
### Release Version V2.0.0
- [x] Use latest master as candidate V2.0.0 of Atlas and deploy to development
- [x] Complete user acceptance testing
- [x] Obtain sign off
- [x] Generate WebAPI Release Notes
- [x] Publish Release
- [x] Communicate production change to team
- [x] Update OHDSI.org
- [x] Communicate release via OHDSI forums

New Features

- Apache Shiro user security integration. For more details, please see the security page on the OHDSI wiki: http://www.ohdsi.org/web/wiki/doku.php?id=development:security
- Achilles summary statistics are now exposed through REST end-points in the CDMResults service. 
- New REST endpoint (/info) will provide the version number of WebAPI that is installed
- Ability to delete an estimation specification 

Fixes

- #170: Additional error handling when retrieving an estimation specification
- #173: Fixed table qualifiers

Important Notes

- V2.0.0 of WebAPI now requires Java 8
- REST Endpoint Routes have changed per #174 which will break backwards compatibility
