### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#218]
### Release Version V2.1.0
- [x] Use latest master as candidate V2.1.0 of Atlas and deploy to development
- [x] Complete user acceptance testing
- [x] Obtain sign off
- [x] Generate WebAPI Release Notes
- [x] Publish Release
- [x] Communicate production change to team
- [x] Update OHDSI.org
- [x] Communicate release via OHDSI forums

New Features

- #219 - Cohort list query optimization
- #214 - Caching record counts from results schema
- #186 - Updated Spring Libraries

Fixes

- #211 - Oracle shiro security db update fixes
- #215 - cohort_summary_stats is empty when definition has mutually exclusive inclusion rule
- #213 - Fixes to get (some of) ATLAS running against Impala
- #209 - Heracles Heel fix
- #207 - run flyway migration before initialization of 'security' bean
- #183 - CDM results - data density query error
- #185 - Miredot licensing update
