### ISSUE TITLE
Release V2.2.0

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#255]
### Release Version V2.2.0
- [x] Use latest master as candidate V2.2.0 of Atlas and deploy to development
- [x] Complete user acceptance testing
- [x] Obtain sign off
- [x] Generate WebAPI Release Notes
- [x] Publish Release
- [x] Communicate production change to team
- [x] Update OHDSI.org
- [x] Communicate release via OHDSI forums

See [V2.2.0](https://github.com/OHDSI/WebAPI/releases/tag/untagged-475927e5254600edf72d) for release notes
