### ISSUE TITLE
Release V2.7.0

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#843]
### Release Version V2.7.0
- [x] Use latest master as candidate V2.7.0 of Atlas & WebAPI and deploy to development. Ensure that all pom.xml references are using released libraries per #626.
- [x] Complete testing and obtain sign off, specifically #700
- [x] Generate WebAPI Release Notes
- [x] Update source code formatting? Per https://github.com/OHDSI/Atlas/pull/1213, only aim to do the formatting and not linting for ATLAS.
- [x] Publish Release
- [ ] Update wikis to reflect any install/setup instructions
- [x] Update OHDSI.org
- [x] Communicate release via OHDSI forums
